### ISSUE TITLE
Is adminCommand really connected to the admin DB?

### ISSUE THREAD

**Issue by DarrinProtag** [liquibase/liquibase-mongodb#111]
I'm trying to use runCommand or adminCommand to invoke shardCollection. I'm on version 4.3.1.

I get this error from Mongo: 'shardCollection may only be run against the admin database', from this:
         adminCommand(command: '{shardCollection: \'darrin.player_info_static\', key: \'{location: 1, _id: 1}\', unique: true} ')
Same as if I'd used runCommand.

Your AdminCommandStatement.run() calls: database.getMongoDatabase().runCommand(command);
I'd expect it to lookup the admin DB.

And I can't figure out how to invoke db.adminCommand() on Mongo using runCommand (as a workaround).

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1336) by [Unito](https://www.unito.io/learn-more)

**Comment by DarrinProtag** [comment]
I *think* you want something like this in AdminCommandStatement.java (I need to figure out how to test this change):
```
     @Override
     public Document run(final MongoConnection connection) {
        MongoLiquibaseDatabase lbdb = (MongoLiquibaseDatabase)connection.getDatabase();
        return connection.getClient().getDatabase(lbdb.getSystemSchema()).runCommand(command);
     }
```

**Comment by DarrinProtag** [comment]
Sorry, I was browsing the older code base. I think this might work:
```
    public Document run(final MongoLiquibaseDatabase database) {
        MongoDatabase adminDB = ((MongoConnection)database.getConnection()).getMongoClient().getDatabase(database.getSystemSchema());
        return adminDB.runCommand(command);
    }
```

**Comment by DarrinProtag** [comment]
To add some detail, here is the command I was attempting:
```
adminCommand(command: '{shardCollection: "darrin.player_info_static", key: {location: 1, _id: 1}, unique: true} ')
```

Also, I forked the project and made the patch I suggested above, and it appears to be working!

**Comment by alexandru-slobodcicov** [comment]
Thank you @DarrinProtag, will go on with your solution. Hopefully will merge it today

**Comment by alexandru-slobodcicov** [comment]
Merged will be available in 4.3.1.1 when released

**Comment by alexandru-slobodcicov** [comment]
Hi @DarrinProtag please note https://github.com/liquibase/liquibase-mongodb/releases/tag/liquibase-mongodb-4.3.1.1 is released. Could you please try it out?

**Comment by DarrinProtag** [comment]
> Hi @DarrinProtag please note https://github.com/liquibase/liquibase-mongodb/releases/tag/liquibase-mongodb-4.3.1.1 is released. Could you please try it out?

No problem. I switched my build to this released version, and it works fine. Thank you. I am now able to set up sharding, shard my collections, and set the shard keys!

For the next person...I'm using groovy formatted changelogs, and doing things like this... And need no manual setup steps, now.
```
        adminCommand(command: '{enableSharding: "${database.name}" } ')
        adminCommand(command: '{shardCollection: "${database.name}.player_info_static", key: {location: 1, _id: 1}, unique: true} ')
```

**Comment by Yuriy-Lukashevich** [comment]
Hi @DarrinProtag. I'm trying to add luquibase to my project. We are using Cosmosdb Mongodb API. 
I appreciate it very much if you could share how to add to xml or json script operation like this:
db.runCommand({customAction: "CreateCollection", collection: "name",  offerThroughput: 400, shardKey: "partition_key", indexes: [{key: {_id: 1}}, {key: {partition_key: 1, some_key: 1},unique: true}]});

**Comment by DarrinProtag** [comment]
https://docs.liquibase.com/workflows/database-setup-tutorials/mongodb.html - if you twist open the Examples section, there are examples of XML commands to create collections. I haven't found great examples of json (or gradle; which we use) formatted commands. I just tried permutations of syntax until it started making sense to me.

These are the libraries we included:
plugins{
    id 'org.liquibase.gradle' version '2.0.4'
}
dependencies{
    liquibaseRuntime "org.liquibase.ext:liquibase-mongodb:${project.liquibaseMongodbVersion}" //4.3.1
    liquibaseRuntime "org.liquibase:liquibase-core:${project.liquibaseCoreVersion}" //4.3.1
    liquibaseRuntime "org.liquibase:liquibase-groovy-dsl:${project.liquibaseGroovyVersion}" // 3.0.0
}

I assume there is a json-dsl library you'd need to include if you wanted to parse json command files.

I assume cosmo will accept a regular mongo connection string, as opposed to needing a custom cosmo sdk compiled against liquibase. No doubt, Azure (or whoever) wants fancy auth set up locally before it will respond, though.

To run stuff from gradle build files...
// Run liquibase.update to get schema/indexes up to date.
// In the future, to manage multiple clusters in one mongo,
//   use -PrunList stuff from the docs: https://github.com/liquibase/liquibase-gradle-plugin
liquibase {
    activities {
        local {
            // parameters in each activity are from --<commandline-arg> for liquibase...
            // https://docs.liquibase.com/commands/home.html
            changeLogFile 'datastore/src/main/resources/liquibase/changelogs.groovy'
            dataOutputDirectory 'datastore/src/main/resources/liquibase/changelog_out'
            url 'mongodb://localhost:27017/darrin'
            // username ''
            // password ''

            // Needs to run with -Ddatabase.name=darrin to fix up changelog contents (e.g. stuff like "${database.name}.unique_item"}.
            changeLogParameters([ "database.name" : "darrin"])
            classPath "$rootDir"
        }
    }
}

Sorry I can't be more help about the json format.

**Comment by Yuriy-Lukashevich** [comment]
Darrin thank you for your reply. I red tutorial, but it has no useful examples in my case. I have no issues with connection or run simple commands on CosmosDB MongoDB, but runCommand with customAction won't work.

**Comment by DarrinProtag** [comment]
Its a bit of a leap into deep water, but the liquibase-mongo source is online. If you spend awhile staring at it, you might figure out whether customAction is supported or if there is a generic command that you could send it through. And if not, maybe you could see how to add a new command that supports it. Alexandru was quite kind about taking suggested changes, so you may not have to use a private fork for very long.

https://github.com/liquibase/liquibase-mongodb/tree/main/src/main/java/liquibase/ext/mongodb

**Comment by nwinkler** [comment]
@Yuriy-Lukashevich I'm trying to run Liquibase-MongoDB on CosmosDB, but I'm running into some errors when Liquibase is starting up, complaining about the `collMod` command not being supported on CosmosDB.

Did you have to use any special configuration for Liquibase to make it work on CosmosDB?
