### ISSUE TITLE
 ExecutorService.getInstance().getExecutor( is deprecated but still being referenced from MongoLockService

### ISSUE THREAD

**Issue by sudhihs** [liquibase/liquibase-mongodb#26]
https://github.com/liquibase/liquibase-mongodb/blob/388035c54b58b4ad640b93daf5b574c26f4731a1/src/main/java/liquibase/ext/mongodb/lockservice/MongoLockService.java#L88

Hi the line above calls the deprecated method  causing nullpointer error when using  the method 

  ExecutorService.getInstance().setExecutor("mongoDb", database, mongoExecutor);

Please can you address this issue in the next build?

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-489) by [Unito](https://www.unito.io/learn-more)

**Comment by alexandru-slobodcicov** [comment]
Fixed in releases higher than 4.0.0
