### ISSUE TITLE
How to execute same change log on different schemas on the same mongo cluster. 

### ISSUE THREAD

**Issue by muralikrishna-kumpatla** [liquibase/liquibase-mongodb#302]
We have multiple tenant specific databases on mongo replicaset. Need to run the same change log on all databases. 
As of now we are able to execute the change log on single database from properties file. 

ChangeLogFile: dbchangelog.json
url: mongodb://localhost:27017/liquibasepocdb?authSource=admin
username: xxxxxxx
password: xxxxxxx

In my case i am able to create index on test liquibasepocdb db only
I have many such databases , how we can execute same change on all databases?
I read the contexts documents but no luck how we can do this using contexts?

**Comment by tati-qalified** [comment]
Hello @muralikrishna-kumpatla , sorry for the late response.
You can change the schema by modifying the url in the liquibase.properties file or any other code where you set it.

For example:
```
changeLogFile=changelog.create-collection.xml
url: mongodb://localhost:27017/db1
```

and then modify it to be
```
changeLogFile=changelog.create-collection.xml
url: mongodb://localhost:27017/db2
```

I hope this helps!
