### ISSUE TITLE
Java call failing while calling liquibase update

### ISSUE THREAD

**Issue by imurpalvicky** [liquibase/liquibase-mongodb#36]
I am trying to integrate with java call and use the module(liquibase-mongodb) but it is failing with below log

0:52:02.903 [main] DEBUG liquibase.servicelocator.ServiceLocator - ServiceLocator finding classes matching interface liquibase.executor.Executor
20:52:02.903 [main] DEBUG liquibase.servicelocator.DefaultPackageScanClassResolver - Searching for implementations of liquibase.executor.Executor in packages: [liquibase.change, liquibase.command, liquibase.changelog, liquibase.database, liquibase.parser, liquibase.precondition, liquibase.datatype, liquibase.serializer, liquibase.sqlgenerator, liquibase.executor, liquibase.snapshot, liquibase.logging, liquibase.diff, liquibase.structure, liquibase.structurecompare, liquibase.lockservice, liquibase.sdk.database, liquibase.ext, liquibase.pro, com.datical.liquibase]
20:52:02.903 [main] DEBUG liquibase.servicelocator.DefaultPackageScanClassResolver - Searching for: is assignable to Executor in package: liquibase/change
20:52:02.903 [main] DEBUG liquibase.servicelocator.DefaultPackageScanClassResolver - Searching for: is assignable to Executor in package: liquibase/command
20:52:02.903 [main] DEBUG liquibase.servicelocator.DefaultPackageScanClassResolver - Searching for: is assignable to Executor in package: liquibase/changelog
20:52:02.903 [main] DEBUG liquibase.servicelocator.DefaultPackageScanClassResolver - Searching for: is assignable to Executor in package: liquibase/database
20:52:02.903 [main] DEBUG liquibase.servicelocator.DefaultPackageScanClassResolver - Searching for: is assignable to Executor in package: liquibase/parser
20:52:02.904 [main] DEBUG liquibase.servicelocator.DefaultPackageScanClassResolver - Searching for: is assignable to Executor in package: liquibase/precondition
20:52:02.904 [main] DEBUG liquibase.servicelocator.DefaultPackageScanClassResolver - Searching for: is assignable to Executor in package: liquibase/datatype
20:52:02.904 [main] DEBUG liquibase.servicelocator.DefaultPackageScanClassResolver - Searching for: is assignable to Executor in package: liquibase/serializer
20:52:02.904 [main] DEBUG liquibase.servicelocator.DefaultPackageScanClassResolver - Searching for: is assignable to Executor in package: liquibase/sqlgenerator
20:52:02.904 [main] DEBUG liquibase.servicelocator.DefaultPackageScanClassResolver - Searching for: is assignable to Executor in package: liquibase/executor
20:52:02.904 [main] DEBUG liquibase.servicelocator.DefaultPackageScanClassResolver - Searching for: is assignable to Executor in package: liquibase/snapshot
20:52:02.904 [main] DEBUG liquibase.servicelocator.DefaultPackageScanClassResolver - Searching for: is assignable to Executor in package: liquibase/logging
20:52:02.904 [main] DEBUG liquibase.servicelocator.DefaultPackageScanClassResolver - Searching for: is assignable to Executor in package: liquibase/diff
20:52:02.904 [main] DEBUG liquibase.servicelocator.DefaultPackageScanClassResolver - Searching for: is assignable to Executor in package: liquibase/structure
20:52:02.904 [main] DEBUG liquibase.servicelocator.DefaultPackageScanClassResolver - Searching for: is assignable to Executor in package: liquibase/structurecompare
20:52:02.904 [main] DEBUG liquibase.servicelocator.DefaultPackageScanClassResolver - No classes found in package: liquibase/structurecompare
20:52:02.904 [main] DEBUG liquibase.servicelocator.DefaultPackageScanClassResolver - Searching for: is assignable to Executor in package: liquibase/lockservice
20:52:02.904 [main] DEBUG liquibase.servicelocator.DefaultPackageScanClassResolver - Searching for: is assignable to Executor in package: liquibase/sdk/database
20:52:02.904 [main] DEBUG liquibase.servicelocator.DefaultPackageScanClassResolver - Searching for: is assignable to Executor in package: liquibase/ext
20:52:02.904 [main] DEBUG liquibase.servicelocator.DefaultPackageScanClassResolver - Searching for: is assignable to Executor in package: liquibase/pro
20:52:02.904 [main] DEBUG liquibase.servicelocator.DefaultPackageScanClassResolver - Searching for: is assignable to Executor in package: com/datical/liquibase
20:52:02.905 [main] DEBUG liquibase.servicelocator.DefaultPackageScanClassResolver - Found: [class liquibase.executor.jvm.JdbcExecutor, class liquibase.executor.LoggingExecutor, class liquibase.ext.mongodb.executor.MongoExecutor, class com.datical.liquibase.ext.OracleSqlPlusExecutor]
20:52:02.905 [main] DEBUG liquibase.servicelocator.ServiceLocator - liquibase.executor.jvm.JdbcExecutor matches liquibase.executor.Executor
20:52:02.920 [main] DEBUG liquibase.servicelocator.ServiceLocator - liquibase.ext.mongodb.executor.MongoExecutor matches liquibase.executor.Executor
20:52:02.920 [main] DEBUG liquibase.servicelocator.ServiceLocator - com.datical.liquibase.ext.OracleSqlPlusExecutor matches liquibase.executor.Executor
20:52:02.921 [main] **_DEBUG liquibase.servicelocator.ServiceLocator - ServiceLocator.findClasses for liquibase.executor.Executor
liquibase.exception.LockException: liquibase.exception.UnexpectedLiquibaseException: java.lang.ClassCastException: class **_liquibase.executor.ExecutorService cannot be cast to class liquibase.SingletonObject (liquibase.executor.ExecutorService and liquibase.SingletonObject are in unnamed module of loader 'app')_**_**

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-628) by [Unito](https://www.unito.io/learn-more)

**Comment by alexandru-slobodcicov** [comment]
Not reproducing from v4.0.0 Java call example in README: 
`
public class Application {
    public static void main(String[] args) {
        MongoLiquibaseDatabase database = (MongoLiquibaseDatabase) DatabaseFactory.getInstance().openDatabase(url, null, null, null, null);
        Liquibase liquibase = new Liquibase("liquibase/ext/changelog.generic.test.xml", new ClassLoaderResourceAccessor(), database);
        liquibase.update("");
    }
}
`

**Comment by alexandru-slobodcicov** [comment]
Not reproducing from v4.0.0 Java call example in README:
`
public class Application { public static void main(String[] args) { MongoLiquibaseDatabase database = (MongoLiquibaseDatabase) DatabaseFactory.getInstance().openDatabase(url, null, null, null, null); Liquibase liquibase = new Liquibase("liquibase/ext/changelog.generic.test.xml", new ClassLoaderResourceAccessor(), database); liquibase.update(""); } }
`
