### ISSUE TITLE
Rollback doesn't work with liquibase-mongodb-4.0.0.2 extension

### ISSUE THREAD

**Issue by szandany** [liquibase/liquibase-mongodb#38]
When rolling back a changeSet, the corresponding data set (“row”) in the DATABASECHANGELOG Collection (“table”) will be removed.  However, the object will NOT be rolled back.

I used the changeLog from here: 
https://github.com/liquibase/liquibase-mongodb/blob/main/src/test/resources/liquibase/ext/changelog.create-collection.test.xml

STR

1. Deploy the changeLog
1. Run `liquibase update`
1. Run `liquibase rollbackCount 1`
1. 
1. Run `liquibase update` again

Actual result:
The changeSet will fail with the message "collection already exists"

Expected result
The update should have been successful
The collection should have been dropped during the rollback

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-643) by [Unito](https://www.unito.io/learn-more)

**Comment by mmarcon** [comment]
I also tested with explicit rollbacks (see my test here: https://github.com/mmarcon/liquibase-mongo-docker/tree/master/example/changelog) and it didn't see to do anything.

**Comment by alexandru-slobodcicov** [comment]
PR raised #54, please test from your side
