### ISSUE TITLE
missing liquibase-mongodb jar file for 4.25.0

### ISSUE THREAD

**Issue by jgarec** [liquibase/liquibase-mongodb#479]
Hello,

The following dependency is unavailable : 

```
<dependency>
    <groupId>org.liquibase.ext</groupId>
    <artifactId>liquibase-mongodb</artifactId>
    <version>4.25.0</version>
</dependency>
```

Is it a release problem or an error in the documentation : https://contribute.liquibase.com/extensions-integrations/directory/database-tutorials/mongodb/#maven-users-additional-step ?

Another question, is it possible to use version 4.24.0 of liquibase-mongodb with liquibase 4.25.0/4.25.1 ? 

BR,
Jérôme

**Comment by vitaliimak** [comment]
Hi @jgarec 
Starting with liquibase-mongodb-4.21.0, the extension versions are no longer synchronized with the liquibase-core release. https://github.com/liquibase/liquibase-mongodb/releases/tag/liquibase-mongodb-4.21.0 
This is a documentation issue. Thanks for bringing this up. 

You can safely use the latest liquibase release (currently 4.25.1) with the latest liquibase-mongodb extension (4.24.0).

**Comment by jgarec** [comment]
Oh thx it's now clear for me !
