### ISSUE TITLE
Atlas search index

### ISSUE THREAD

**Issue by fayfayning** [liquibase/liquibase-mongodb#482]
Just wondering if there are any plans to add the ability to create an Atlas search index. Thanks.

**Comment by vitaliimak** [comment]
Hello @fayfayning 
It is beyond the current planning horizon for liquibase-mongodb extension.

However, this functionality should work in the Liquibase MongoDB Pro extension: https://docs.liquibase.com/mongodb 

https://www.mongodb.com/docs/atlas/atlas-search/create-index/#create-an-fts-index-programmatically
