### ISSUE TITLE
Is there a way to specify the database name when it's not included in the connection string?

### ISSUE THREAD

**Issue by va1erian** [liquibase/liquibase-mongodb#505]
Hello,
We are deploying on a cloud environment where the connection string we receive does not include the database name. Is there a way to specify it manually ? I tried LIQUIBASE_COMMAND_DEFAULT_CATALOG_NAME and LIQUIBASE_COMMAND_DEFAULT_SCHEMA_NAME and it doesn't seem to work.

**Comment by va1erian** [comment]
mongodb, but I got the env team to include the database name in the string so everything is fine.

**Comment by wwillard7800** [comment]
Okay, thanks for the update.
