### ISSUE TITLE
MongoDB connection cannot be made if the Liquibase username and password properties are used with access control enabled

### ISSUE THREAD

**Issue by szandany** [liquibase/liquibase-mongodb#63]
When attempting to create a connection to a mongoDB with Liquibase, the connection will fails if **access control is enabled** and the **username** and **password** properties/flags are used.

**STR**

1. Spin up a docker container with access control (password enabled)
`docker run -d -p 27017:27017 -e MONGO_INITDB_ROOT_USERNAME=mongoAdmin -e MONGO_INITDB_ROOT_PASSWORD=password --name mongodb2 mongo`
1. Create a simple changeLog like the one in the link below:
https://github.com/liquibase/liquibase-mongodb/blob/main/src/test/resources/liquibase/ext/changelog.create-collection.test.xml
1. Place the JDBC + extension in the &lt;liquibase home&gt;/lib directory (4.0.0.2.jar + mongo-java-driver-3.12.7.jar).
1. Run an update:
`liquibase --changeLogFile=dbchangelog_test.xml --url=mongodb://localhost:27017/MYDB?authSource=admin --username=mongoAdmin --password=password status`

**Result**:
The following below error will get produced.
`Unexpected error running Liquibase: com.mongodb.MongoCommandException: Command failed with error 13 (Unauthorized): 'command aggregate requires authentication' on server localhost:27017. The full response is {"ok": 0.0, "errmsg": "command aggregate requires authentication", "code": 13, "codeName": "Unauthorized"}`

**Workaround**:

1. Configure the url to include the username and password.
1. Do NOT use the Liquibase username and password properties.
For example:
`liquibase --changeLogFile=dbchangelog_test.xml --url=mongodb://mongoAdmin:password@localhost:27017/MYDB?authSource=admin status`

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-985) by [Unito](https://www.unito.io/learn-more)

**Comment by r2liquibase** [comment]
Does this happen with 4.1.1.2, @szandany ?

**Comment by szandany** [comment]
Hi @r2liquibase. This is resolved with 4.1.1.2.  Let's make sure that the **jar** file is available for consumption in here https://github.com/liquibase/liquibase-mongodb/releases/tag/liquibase-mongodb-4.1.1.2.

Thanks!
