### ISSUE TITLE
Does it support preconditions

### ISSUE THREAD

**Issue by vshalgarg** [liquibase/liquibase-mongodb#69]
Does this extension supports preconditions. If yes, please provide some examples. I believe it will be good and easy if there is a page describing all the tags available.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1040) by [Unito](https://www.unito.io/learn-more)

**Comment by alexandru-slobodcicov** [comment]
@vshalgarg, thanks for raising this. haven't tried if works out of the box. Will give it a try and fix if not working.

**Comment by vshalgarg** [comment]
Hi @alexandru-slobodcicov , I don't know if this is working and even couldn't try it as I am unable to find the syntax.. can you provide me some syntax so that I can try it on my own. I tried following from https://docs.liquibase.com/concepts/advanced/preconditions.html

"preConditions": [
	    {
           "sqlCheck": {
	  		  "expectedResult": 0,
	  		  "sql": "db.getCollection('collection1').find({})"
	       }
	    }
	      ]

But it gives me IllegalArgumentException. Will appreciate if you could help asap as I am blocked on it

**Comment by vshalgarg** [comment]
Hi @alexandru-slobodcicov ,
any update or can you provide some TAT for this

**Comment by alexandru-slobodcicov** [comment]
Hi @vshalgarg, will be required to extend AbstractPrecondition in order to be possible to use. 
Please let me know which precondition you need? A collection exists, index etc. or you need a generic one to pass some query command? Will try to pick this up next days

**Comment by vshalgarg** [comment]
Hi @alexandru-slobodcicov ,
The preconditions I need mostly are checking if a document already exist in collection or not. But other conditions might also be useful.

**Comment by vshalgarg** [comment]
Hi @alexandru-slobodcicov ,
any update on this. Requesting you to please pick on priority, as I am blocked on this and Mongo db also doesn't throw an exception on duplicate documents.

**Comment by alexandru-slobodcicov** [comment]
Hi @vshalgarg please see the associated PR. 
Added the precondition DocumentExistsPrecondition
added examples for XML and JSON: changelog.insert-precondition.test.xml, changelog.insert-precondition.test.json
In the examples tested the new introduced documentExists with filter and without as well as the out of the box one like changeSetExecuted. 

Please let me know if this fits your needs. You can build it locally from main branch or wait for the next release most probably 4.2.2.1

Additionally if you are a Java developer you can write a custom Java precondition as well as custom change and do your precondition checks. 

Related to duplicate documents exceptions in Mongo, you can add unique indexes on some fields (id) and you will get exceptions during inserts.

**Comment by vshalgarg** [comment]
Hi @alexandru-slobodcicov ,
Could we please get this PR merged
https://github.com/liquibase/liquibase-mongodb/pull/76

**Comment by nayakam** [comment]
> Hi @vshalgarg, will be required to extend AbstractPrecondition in order to be possible to use. Please let me know which precondition you need? A collection exists, index etc. or you need a generic one to pass some query command? Will try to pick this up next days

Is there anyway to add precodition check for the index?  Thanks.

**Comment by jmayday** [comment]
In my case I would like to prepare a change set where I can add indexes **if they are missing** (I've added Liquibase to project, and on some MongoDB environments indexes are present, on some other - they are missing). 

This is change set:
```
<changeSet id="changeset_20220822_1250_1" author="jmayday">
    <preConditions onFail="WARN">
            <indexExists indexName="userId_1"/>
    </preConditions>
    <ext:createIndex collectionName="testCollection">
        <ext:keys>
            { userId: 1, type: 1}
        </ext:keys>
        <ext:options>
            { unique: false, name: "userId_1" }
        </ext:options>
    </ext:createIndex>
</changeSet>
```

Without any precondition script fails:
```
Caused by: com.mongodb.MongoCommandException: Command failed with error 86 (IndexKeySpecsConflict): 'Index must have unique name.The existing index: { v: 2, key: { userId: 1 }, name: "userId_1", ns: "dev1.testCollection" } has the same name as the requested index: { v: 2, key: { userId: 1, type: 1 }, name: "userId_1", ns: "dev1.testCollection" }' on server localhost:27017. The full response is {"ok": 0.0, "errmsg": "Index must have unique name.The existing index: { v: 2, key: { userId: 1 }, name: \"userId_1\", ns: \"dev1.testCollection\" } has the same name as the requested index: { v: 2, key: { userId: 1, type: 1 }, name: \"userId_1\", ns: \"dev1.testCollection\" }", "code": 86, "codeName": "IndexKeySpecsConflict"}
	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:198)
```

So this is also not working:
```
<changeSet id="changeset_20220822_1250_1" author="jmayday">
    <preConditions onFail="MARK_RAN">
        <not>
            <indexExists indexName="userId_1"/>
        </not>
    </preConditions>
    <ext:createIndex collectionName="testCollection">
        <ext:keys>
            { userId: 1, type: 1}
        </ext:keys>
        <ext:options>
            { unique: false, name: "userId_1" }
        </ext:options>
    </ext:createIndex>
</changeSet>
```

fails with error:
```
Exception in thread "main" liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset changesets/changeset_20220819_1428.xml::changeset_20220822_1250_1::jakub.madej@sanomapro.fi:
     Reason: 
          changelog.xml : Index Exists Precondition: userId_1 : class liquibase.ext.mongodb.database.MongoConnection cannot be cast to class liquibase.database.jvm.JdbcConnection (liquibase.ext.mongodb.database.MongoConnection and liquibase.database.jvm.JdbcConnection are in unnamed module of loader 'app')
```
