### ISSUE TITLE
Is there a way to tag the current database state?

### ISSUE THREAD

**Issue by mmarcon** [liquibase/liquibase-mongodb#70]
It's great that now rollbacks work well! I am trying the rollback to a tag, but I don't seem to be able to create a tag in the first place.

I tried to put a tag in the XML of the changelog, and I tried the `tag` command to tag manually. I wasn't successful in either case.

If I change the `tag` field manually in the documented inside the `DATABASECHANGELOG` collection then I can rollback with no issues so the problem is also with the tagging itself. What am I doing wrong?

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1065) by [Unito](https://www.unito.io/learn-more)

**Comment by alexandru-slobodcicov** [comment]
Thank you @mmarcon . Please not the associated PR and the comments. 
Fixed last state tag. tagDatabase works out of the box. Added integration tests for xml and json/
MongoLiquibaseIT#testTags->changelog.insert-tags.test.xml MongoLiquibaseJsonIT#testTags->changelog.insert-tags.json
