### ISSUE TITLE
Support mongodb-driver-sync v4.x

### ISSUE THREAD

**Issue by pstetsuk** [liquibase/liquibase-mongodb#71]
I've tried to update driver version in POM and seems all works as expected. All integration tests are passed.

Are there any plans to support it in nearest releases?

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1074) by [Unito](https://www.unito.io/learn-more)

**Comment by jsonking** [comment]
Hi @pstetsuk 

I'm also interested in liquibase working with newer versions of the mongodb driver; and in general being easier to upgrade the driver in client projects without the need to recompile/release this project.

I had an idea for using `runCommand` to achieve this and mentioned it in detail in issue https://github.com/liquibase/liquibase-mongodb/issues/67
It's probably quite straightforward to go though the various statements and convert them; which might then allow this library to work with both `3.12.x` and `4.x` versions of the driver in client projects. 

What do you think? Would you like to help by contributing a PR if this idea gets traction?

**Comment by alexandru-slobodcicov** [comment]
Hi @pstetsuk , @jsonking changed the driver, see the associated PR. It is compatible with 3x drivers as well due to @jsonking suggestions
