### ISSUE TITLE
createIndex with TTL (expireAfterSeconds) is ignored and normal index created

### ISSUE THREAD

**Issue by LawrenceMouarkach** [liquibase/liquibase-mongodb#74]
Hi,

When using this library I noticed whilst trying to create a TTL that it didnt work and a normal index was created please see below:

Actioned in change-log.xml
![image](https://user-images.githubusercontent.com/26540072/103666416-86b4f300-4f6c-11eb-92f4-18881d81b84e.png)

What was created in mongo:
![image](https://user-images.githubusercontent.com/26540072/103666481-9b918680-4f6c-11eb-954f-18dab2e37075.png)

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1096) by [Unito](https://www.unito.io/learn-more)

**Comment by LawrenceMouarkach** [comment]
@alexandru-slobodcicov thoughts? I might fork this repo and look at fixing it if u do not have time at the moment, I will create a pr here if u want?

**Comment by LawrenceMouarkach** [comment]
More info:

![image](https://user-images.githubusercontent.com/26540072/103767733-11532c00-5019-11eb-9038-f79cb341539a.png)


![image](https://user-images.githubusercontent.com/26540072/103767702-04ced380-5019-11eb-8de4-13b3d0e786bc.png)

**Comment by LawrenceMouarkach** [comment]
Change must be made here will work on it now:
![image](https://user-images.githubusercontent.com/26540072/103768003-95a5af00-5019-11eb-9acf-eab9d9aa320f.png)

**Comment by LawrenceMouarkach** [comment]
Wouldnt let me create a pull request, please add following:
**BsonUtils**
`if (options.containsKey("expireAfterSeconds")) {
            indexOptions.expireAfter(options.getLong("expireAfterSeconds"), TimeUnit.SECONDS);
        }`
**BsonUtilsTest**
`    @Test
    void expireAfterSecondsTest() {
        assertThat(BsonUtils.orEmptyDocument("{expireAfterSeconds: NumberLong(\"60\")}").getLong("expireAfterSeconds"))
                .isEqualTo(60L);
    }
`

![image](https://user-images.githubusercontent.com/26540072/103768861-2b8e0980-501b-11eb-92db-d9fe3c563d0f.png)
![image](https://user-images.githubusercontent.com/26540072/103768884-334dae00-501b-11eb-8af4-2b635c4569f6.png)

**Comment by alexandru-slobodcicov** [comment]
Thank you @LawrenceMouarkach for the detailed feedback, raised the PR target release 4.2.2.1

**Comment by swarnaditya-maitra-db** [comment]
> Hi,
> 
> When using this library I noticed whilst trying to create a TTL that it didnt work and a normal index was created please see below:
> 
> Actioned in change-log.xml ![image](https://user-images.githubusercontent.com/26540072/103666416-86b4f300-4f6c-11eb-92f4-18881d81b84e.png)
> 
> What was created in mongo: ![image](https://user-images.githubusercontent.com/26540072/103666481-9b918680-4f6c-11eb-954f-18dab2e37075.png)
> 
> ┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1096) by [Unito](https://www.unito.io/learn-more)

Hey, I just had a question. Might be too noob-ish for a beginner, but here I go anyway. What does the number "1", after the keyName indicate? Does it indicate ordering? If so, what are the possible values?
